config/routes.rb
Rails.application.routes.draw do

  root             'welcome#index'
  get 'about'   => 'welcome#about'
  get 'support' => 'welcome#support'

  resources :cards
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController

  before_action :set_card, only: [:show, :edit, :update, :destroy]

  def index
    @cards = Card.all.order("created_at DESC")
  end

  def new
    @card = Card.new
  end

  def create
    @card = Card.new(card_params)

    if @card.save
      redirect_to(@card, :flash => :success)
    else
      flash_now!(:error)
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @card.update(card_params)
      redirect_to(@card, :flash => :success)
    else
      flash_now!(:error)
      render 'edit'
    end
  end

  def destroy
    @card.destroy
    redirect_to(cards_path, :flash => :warning)
  end

  private
    def set_card
      @card = Card.find(params[:id])
    end

    def card_params
      params.require(:card).permit(:title, :content)
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end

  def support
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/cards/_form.html.erb
<%= simple_form_for @card do |f| %>
  <%= f.input :title %>
  <%= f.input :content%>
  <%= f.button :submit, class: "btn btn-primary" %>

<% end %>

app/views/cards/edit.html.erb
<h1>Edit Card Details</h1>

<%= render "form" %>

app/views/cards/index.html.erb
<h1 class="text-xs-center">Cards List</h1>

<div class="row text-xs-right bmarg">
  <%= link_to "Add New Card", new_card_path, class: "btn btn-success" %>
</div>

<div class="row">
  <% @cards.each do |card| %>
    <div class="card text-xs-center">
      <div class="card-header text-xs-right">
        Created <%= time_ago_in_words(card.created_at) %> ago
      </div>
      <div class="card-block">
        <h4 class="card-title"><%= card.title %></h4>
        <p class="card-text"><%= truncate(card.content, length: 50) %></p>
        <%= link_to "View Card", card, class: "btn btn-primary btn-sm" %>
        <%= link_to "Edit Card", edit_card_path(card), class: "btn btn-warning btn-sm" %>
        <%= link_to "Delete Card", card, method: :delete, data: { confirm: "Are you sure!?" }, class: "btn btn-danger btn-sm" %>
      </div>
      <div class="card-footer text-muted">

      </div>
    </div>
  <% end %>
</div>

app/views/cards/new.html.erb
<h1>New Card</h1>

<%= render "form" %>

app/views/cards/show.html.erb
<h1>Card Details</h1>

<h4><%= @card.title %></h4>
<small>Created: <%= time_ago_in_words(@card.created_at) %> ago</small>
<p><%= simple_format(@card.content) %></p>

<%= link_to "Cards List", cards_path, class: "btn btn-primary" %>
<%= link_to "Edit Card", edit_card_path(@card), class: "btn btn-warning" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cardsapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/nav" %>
    <div class="container">
      <div id="flash_messages"><%= flash_messages(:close, :fade, :heading) %></div>
    </div>
    <div class="container">

      <%= yield %>
    </div>

    <%= render "shared/footer" %>
  </body>
</html>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="container text-xs-center">
    <span class="text-muted">&copy; 2016 Barracuda Computer Inc. All Rights Reserved.</span>
  </div>
</footer>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-fixed-top navbar-dark bg-primary">
  <div class="container">
    <button class="navbar-toggler hidden-lg-up" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"></button>
    <div class="collapse navbar-toggleable-md" id="navbarResponsive">
      <h1 class="navbar-brand mb-0">CardsApp</h1>
      <ul class="nav navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="<%= root_path %>">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= cards_path %>">View Cards</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= about_path %>">About</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= support_path %>">Support</a>
        </li>
        <li class="nav-item float-xs-right">
          <a class="nav-link" href="#">Log In</a>
        </li>
        <li class="nav-item float-xs-right">
          <a class="nav-link" href="#">Register</a>
        </li>
      </ul>
      <!-- <form class="form-inline float-lg-right">
        <input class="form-control" type="text" placeholder="Search">
        <button class="btn btn-sm btn-secondary" type="submit">Search</button>
      </form> -->
    </div>
  </div>
</nav>

app/views/welcome/about.html.erb
<h1>About Page</h1>

app/views/welcome/index.html.erb
<section class="jumbotron text-xs-center">
  <div class="container">
    <h1 class="display-3">CardsApp</h1>
    <p class="lead text-muted">Something short and leading about the collection below—its contents, the creator, etc. Make it short and sweet, but not too short so folks don't simply skip over it entirely.</p>
    <p>
      <a href="#" class="btn btn-primary">Join CardsApp Now!</a>
      <a href="#" class="btn btn-secondary">Features</a>
    </p>
  </div>
</section>

app/views/welcome/support.html.erb
<h1>Support Page</h1>